name: Docker Base Image Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Base image ç‰ˆæœ¬è™Ÿï¼ˆä¾‹å¦‚ dev-0.0.12 æˆ– 1.2.3ï¼‰'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: ğŸ§¾ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Prepare build
        id: set-version
        run: echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: ğŸ§± Build docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          push: false
          tags: nx-base:${{ github.event.inputs.version }}

  push:
    needs: build
    uses: ./.github/workflows/base-push.yml
    with:
      image_name: nx-base
      version: ${{ needs.build.outputs.version }}
    secrets: inherit    # å°‡ç™»å…¥ dockerhub çš„æ†‘è­‰å‚³çµ¦è¢«å‘¼å«ç«¯
